practical4
ADMIN@Jayeshkhadke MINGW64 ~/Desktop/practical3
$ git config --global user.name "jayesh"

ADMIN@Jayeshkhadke MINGW64 ~/Desktop/practical3
$ git config --global user.email "jayeshkhadke510@gmail.com"

ADMIN@Jayeshkhadke MINGW64 ~/Desktop/practical3
$ git init
Initialized empty Git repository in C:/Users/ADMIN/Desktop/practical3/.git/

ADMIN@Jayeshkhadke MINGW64 ~/Desktop/practical3 (master)
$ git commit
On branch master

Initial commit

nothing to commit (create/copy files and use "git add" to track)

ADMIN@Jayeshkhadke MINGW64 ~/Desktop/practical3 (master)
$ touch abc.txt

ADMIN@Jayeshkhadke MINGW64 ~/Desktop/practical3 (master)
$ git status
On branch master

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        abc.txt

nothing added to commit but untracked files present (use "git add" to track)

ADMIN@Jayeshkhadke MINGW64 ~/Desktop/practical3 (master)
$ git add abc.txt

ADMIN@Jayeshkhadke MINGW64 ~/Desktop/practical3 (master)
$ git add --a

ADMIN@Jayeshkhadke MINGW64 ~/Desktop/practical3 (master)
$ git status
On branch master

No commits yet

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)
        new file:   abc.txt

ADMIN@Jayeshkhadke MINGW64 ~/Desktop/practical3 (master)
$ git commit "practical3"
error: pathspec 'practical3' did not match any file(s) known to git

ADMIN@Jayeshkhadke MINGW64 ~/Desktop/practical3 (master)
$ git commit -m "practical3"
[master (root-commit) 6f62ec9] practical3
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 abc.txt

ADMIN@Jayeshkhadke MINGW64 ~/Desktop/practical3 (master)
$ git log
commit 6f62ec941d9712201f2fe14292d19ec72d491966 (HEAD -> master)
Author: jayesh <jayeshkhadke510@gmail.com>
Date:   Thu Jun 30 20:42:40 2022 +0530

    practical3